application: campus-connect-2015
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:       # static then dynamic


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials



- url: /_ah/spi/.*
  script: clubapis.api
  secure: always
- url: /crontasks
  script: cronmodule.py 
   
- url: /get_upload_url
  script: main.app

- url: /upload_photo
  script: main.app

- url: /pc_upload_photo
  script: pc_photo.app

libraries:

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest

- name: ssl
  version: latest

- name: webapp2
  version: "2.5.2"
